### ISSUE TITLE
Keyfile (.keyx) does not work

### ISSUE THREAD

**Issue by midi292** [FrankHausmann/KeePassMini#44]
Version 2.4.1

I have created a test database with password and keyfile using Keepass (2.52 Windows). The database is located in a cloud (sync.com) and the keyfile is stored locally on the iPhone (SE 1st gen., iOS 15.7.1).
I have added/imported the database and keyfile. After entering the password and selecting the keyfile, the message "_Could not open database - Passwörter stimmen nicht überein_" appears.
Touch ID/Face ID are deactivated in the app.
I have tried with different databases and keyfiles. Without the combination with password (only keyfile), the login does not work either.
In a test to compare with another app, the login works. This means that the database and keyfile are OK.

**Comment by FrankHausmann** [comment]
I just tried to recreate this, I created a Kdbx V4 with KeeaPassXC on the Mac Book and then created an additional key file, I uploaded both data to the iPhone via AirDrop and can open the kdbx including its key file without any problem. I see this issue in connection with IOSKEEPASS.

I would assume that something went wrong when copying the key file.

**Comment by midi292** [comment]
Thank you for the quick reply. I also tried again with kdbx V4, but still without success. I will also try KeePassXC soon and create the database and key with it. Maybe that will make the difference. It's unlikely that something went wrong during the transfer, because the same data works when tested with Ke***sium.

**Comment by midi292** [comment]
Still no success. I have also tried it with KeePassXC, but with PC and Win10. I have tried to transfer the key file in different ways. For testing reasons, the database and key file are now located in the cloud (sync.com). The error message is still the same. However, the same database with the key file can be opened with Keepass (2.52) or Ke***sium without any problems.

**Comment by FrankHausmann** [comment]
I have maintain and build up a new version, it will upload to App Store in a couple of days.
I hope it will help.

**Comment by davidtgillard** [comment]
I've also had issues with key files (v2.0 key file); I switched to a version 1.0 key file and it works.

File format versions:
 kdbx version: 4.1
 Key file version: 2.0

**Comment by FrankHausmann** [comment]
It is fixed, but i cant longer rollout the patch under the Name **IOSKeePass** in App Store,about
apple guidline rules for IOS AppNames.

**KeePassMini** is the new Name for the App in AppStore, the deployment is
in review by Apple App Store Team, please have a look from time to time is the App with new Name, but with the same Icon avaiable in Apples App Store.

**Comment by davidtgillard** [comment]
Got it. Thanks for the information, and for all your hard work on this app!
