### ISSUE TITLE
Could not open database. Passwords do not match.

### ISSUE THREAD

**Issue by MarcusGHub** [FrankHausmann/KeePassMini#52]
Version 2.4.9

I have 5 databases (kdbx). Only 1 out of the 5 are unable to be opened in the app. I keep getting the message stated in the title and screenshot below. The database 3MB in size. It was created on a Windows operating system. 

I have read the other threads and update seem to have resolved the other issues. I’m not sure why mine is not working.

I changed the key file to version with no luck.

![IMG_0159](https://user-images.githubusercontent.com/8460723/230063825-715ecdd1-cf12-4d71-bbd1-d46cd69b0d78.png)

**Comment by MarcusGHub** [comment]
Windows app version is 2.53(64-bit)

Keyfile reads like this:

`<?xml version="1.0" encoding="utf-8"?>
<KeyFile>
	<Meta>
		<Version>2.0</Version>
	</Meta>
	<Key>
		<Data Hash="***">
			***
		</Data>
	</Key>
</KeyFile>`

Should I post the entire file?

**Comment by FrankHausmann** [comment]
The Keyfile seems to be a correct XML 2.0 Keyfile format, and no i don´t need the data.
The hash value tagged as Hash="xxx" is the hash from Data from the inner of the data tag.

the hash value must correspondend to the Data as an SHA256, this prevents a brute force attack

But actually everything looks pretty good.
But I would have a guess, which is not directly related to the keyfile.

If there was already a KeePass file on the Apple device with the same name as this one, which cannot be opened, and the Biometrics (FaceID/TouchID) was switched on, then it could be that there is still an old entry in the key bundle management. 
In this case just turn off Biometrics in KeePassMini (this cleared the keychain for KeePassMini), then turn it on again and try to include the KDB(x) again.

If this does not help, the password or keyfile must be wrong in this case.

**Comment by MarcusGHub** [comment]
Nothing seems to work.

I created a new database and keyfile and I get the same error. I have attached them.
[FUG-Pass2.zip](https://github.com/FrankHausmann/KeePassMini/files/11218069/FUG-Pass2.zip)
Password: 7085@KPmar

**Comment by FrankHausmann** [comment]
i have now narrowed down your problem, as shown in the screenshot we remove spaces and newlines from the keyblocks, unfortunately the software you are using uses tabs instead of spaces between the keyblocks, in a next version i will still remove tabs from the keyblocks.
In the meantime you can manually replace the tabs with spaces, these are already removed when converting the keyblocks to the actual key.

By the way, we don't have this problem because we work with KeePassXC on the Windows side, and there we use spaces between the blocks and no tabs.

<img width="1030" alt="grafik" src="https://user-images.githubusercontent.com/67282017/231832143-00818466-a28b-445a-8bcd-d11c3be1d5e1.png">

**Comment by MarcusGHub** [comment]
> i have now narrowed down your problem, as shown in the screenshot we remove spaces and newlines from the keyblocks, unfortunately the software you are using uses tabs instead of spaces between the keyblocks, in a next version i will still remove tabs from the keyblocks. In the meantime you can manually replace the tabs with spaces, these are already removed when converting the keyblocks to the actual key.
> 
> By the way, we don't have this problem because we work with KeePassXC on the Windows side, and there we use spaces between the blocks and no tabs.
> 
> <img alt="grafik" width="1030" src="https://user-images.githubusercontent.com/67282017/231832143-00818466-a28b-445a-8bcd-d11c3be1d5e1.png">

What's the difference between what you use as oppose to what we use? You said you use KeePassXC as oppose to what I use.

Are you saying that this will be fixed in the next release?

How do I go about making the changes you're suggesting?

**Comment by FrankHausmann** [comment]
Please update to 2.5.0 it should be fixed

**Comment by MarcusGHub** [comment]
It works now. Thank you.
